"""add user_id scoping to emotion_logs and memory_summaries

Revision ID: 243eb50cde92
Revises: 2cb89784c5f1
Create Date: 2026-07-15 08:59:47.910242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '243eb50cde92'
down_revision: Union[str, Sequence[str], None] = '2cb89784c5f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Manually adjusted from the raw autogenerate output: user_id is added
    with a temporary server_default so this doesn't fail if you already
    have emotion_logs / memory_summaries rows from Phase 3 (which had no
    concept of users yet). New rows going forward always provide a real
    user_id from the application - this default only ever backfills
    pre-Phase-4 history.
    """
    op.add_column(
        'emotion_logs',
        sa.Column('user_id', sa.String(), nullable=False, server_default='legacy-single-user'),
    )
    op.create_index(op.f('ix_emotion_logs_user_id'), 'emotion_logs', ['user_id'], unique=False)
    op.add_column(
        'memory_summaries',
        sa.Column('user_id', sa.String(), nullable=False, server_default='legacy-single-user'),
    )
    op.create_index(op.f('ix_memory_summaries_user_id'), 'memory_summaries', ['user_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memory_summaries_user_id'), table_name='memory_summaries')
    op.drop_column('memory_summaries', 'user_id')
    op.drop_index(op.f('ix_emotion_logs_user_id'), table_name='emotion_logs')
    op.drop_column('emotion_logs', 'user_id')
    # ### end Alembic commands ###
