"""initial schema: emotion_logs and memory_summaries

Revision ID: 2cb89784c5f1
Revises: 
Create Date: 2026-07-14 07:24:04.599242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cb89784c5f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emotion_logs',
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('emotion', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('memory_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('summary_text', sa.String(), nullable=False),
    sa.Column('message_count_at_creation', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memory_summaries')
    op.drop_table('emotion_logs')
    # ### end Alembic commands ###
